import type { IconType } from 'react-icons'
import {
    FaAward,
    FaBandage,
    FaBath,
    FaBed,
    FaBolt,
    FaBrain,
    FaBriefcaseMedical,
    FaBroom,
    FaCalendarCheck,
    FaCalendarDays,
    FaCapsules,
    FaCar,
    FaCertificate,
    FaChartLine,
    FaCheck,
    FaCircleCheck,
    FaClipboard,
    FaClipboardCheck,
    FaClipboardList,
    FaClock,
    FaComments,
    FaDollarSign,
    FaDumbbell,
    FaFaceSmile,
    FaFileMedical,
    FaGraduationCap,
    FaHandHoldingHeart,
    FaHandshake,
    FaHeart,
    FaHeartPulse,
    FaHospital,
    FaHouse,
    FaHouseChimneyMedical,
    FaHouseUser,
    FaLifeRing,
    FaLightbulb,
    FaLungs,
    FaMap,
    FaMapLocationDot,
    FaMedal,
    FaMugHot,
    FaNotesMedical,
    FaPersonWalking,
    FaPhone,
    FaRoute,
    FaScaleBalanced,
    FaShield,
    FaShieldHeart,
    FaShirt,
    FaStethoscope,
    FaSyringe,
    FaToilet,
    FaUserCheck,
    FaUserDoctor,
    FaUserGroup,
    FaUserNurse,
    FaUserShield,
    FaUsers,
    FaUtensils,
    FaWheelchair
} from 'react-icons/fa6'
import {
    FaBandAid,
    FaCalendarAlt,
    FaHandsHelping,
    FaHeartbeat,
    FaMapMarked,
    FaMedkit,
    FaPhoneAlt,
    FaShieldAlt,
    FaUserMd
} from 'react-icons/fa'

const iconMap = {
    FaAward,
    FaBandAid,
    FaBandage,
    FaBath,
    FaBed,
    FaBolt,
    FaBrain,
    FaBriefcaseMedical,
    FaBroom,
    FaCalendarAlt,
    FaCalendarCheck,
    FaCalendarDays,
    FaCapsules,
    FaCar,
    FaCertificate,
    FaChartLine,
    FaCheck,
    FaCircleCheck,
    FaClipboard,
    FaClipboardCheck,
    FaClipboardList,
    FaClock,
    FaComments,
    FaDollarSign,
    FaDumbbell,
    FaFaceSmile,
    FaFileMedical,
    FaGraduationCap,
    FaHandHoldingHeart,
    FaHandsHelping,
    FaHandshake,
    FaHeart,
    FaHeartPulse,
    FaHeartbeat,
    FaHospital,
    FaHouse,
    FaHouseChimneyMedical,
    FaHouseUser,
    FaLifeRing,
    FaLightbulb,
    FaLungs,
    FaMap,
    FaMapLocationDot,
    FaMapMarked,
    FaMedal,
    FaMedkit,
    FaMugHot,
    FaNotesMedical,
    FaPersonWalking,
    FaPhone,
    FaPhoneAlt,
    FaRoute,
    FaScaleBalanced,
    FaShield,
    FaShieldAlt,
    FaShieldHeart,
    FaShirt,
    FaStethoscope,
    FaSyringe,
    FaToilet,
    FaUserCheck,
    FaUserDoctor,
    FaUserGroup,
    FaUserMd,
    FaUserNurse,
    FaUserShield,
    FaUsers,
    FaUtensils,
    FaWheelchair
} satisfies Record<string, IconType>

export type IconName = keyof typeof iconMap

export function resolveIconComponent(
    icon: IconType | IconName | string | undefined
): IconType | null {
    if (!icon) return null

    if (typeof icon === 'string') {
        return (iconMap as Record<string, IconType>)[icon] ?? null
    }

    return icon
}

export { iconMap }
