export const HomeAidServices = [
    'Alzheimer’s Care',
    'Arthritis Care',
    'Blood Pressure Care',
    'Congestive Heart Failure Care',
    'COPD Care',
    'Coronary Artery Disease Care',
    'Dementia Care',
    'Depression Home Care',
    'Diabetes Care',
    'Elderly Home Health Care',
    'Huntington’s Disease Care',
    'Hypertension Care',
    'Joint Replacement Care',
    'Mental Health',
    'Multiple Sclerosis Care',
    'Palliative Care',
    'Paraplegia & Quadriplegia Care',
    "Parkinson's Disease",
    'Pediatric Care',
    'Respite Care',
    'Senior Care',
    'Transitional Care',
    'Traumatic Brain Injury Care',
    'Ventilator Care',
    'Veterans Care',
    'Wound Care'
]
